#Add Dockerfile commands with which Docker can build images reading the instructions.
FROM adoptopenjdk/openjdk11
WORKDIR /
ADD target/maincourse_java_jfse_mc05_dockerfile_exercise-0.0.1-SNAPSHOT.jar maincourse_java_jfse_mc05_dockerfile_exercise-0.0.1-SNAPSHOT.jar
CMD java -jar maincourse_java_jfse_mc05_dockerfile_exercise-0.0.1-SNAPSHOT.jar